# This is the configuration file for SatisRandomTP.
# Version: 2.0-A1
# Config-Version: 2.0
teleportation:
  settings: # Settings for the random teleportation if levels are disabled.
    enabled: true # if false, and if section 'levels' is disabled, players will no longer be allowed to rtp. If levels are enabled, refer to the 'levels' section.
messages:
  prefix: "&8[&6SatisRandomTP&8] &r"
  reload: "&aConfiguration reloaded!"
  help:
    - "&e&lSatisRandomTP &7- &aHelp &7- &cV0.1-01B"
    - "&7- &a/rtp &7- &aTeleport to a random location."
    - "&7- &a/rtp reload &7- &aReload the configuration."
    - "&7- &a/rtp disable &7- &aDisable the random teleportation."
    - "&7- &a/rtp enable &7- &aEnable the random teleportation."
    - "&7- &a/rtp <1/2/3> &7- &aTeleport to a random location with a specific level."
  disabled: "&cPlayers can't teleport to a random location for now. This functionality is in maintenance."
  enabled: "&aPlayers can now teleport to a random location."
  will-teleport: "&aYou will be teleported to a random location in &7%delay%&a..."
  permissions: "&cYou don't have the permission to use this command." #same permission message for all commands/levels.
  teleport: "&aYou've been teleported to the location &7%location%&a."
  already-teleporting: "&cYou're already teleporting to a random location. Try again later."
  moved: "&cYou've moved, teleportation cancelled."
  cooldown: "&cYou must wait &7%d before teleporting to a random location again."
levels:
  enabled: true #if false, refer to the 'settings' section.
  level-1:
    world: "world"
    max-distance: 150
    min-distance: 0
    delay: 5
    finding-safe-location-delay: 1
    cooldown: 3
  level-2:
    world: "world"
    max-distance: 1500
    min-distance: 150
    delay: 3
    finding-safe-location-delay: 1
    cooldown: 60
  level-3:
    world: "world"
    max-distance: 15000
    min-distance: 1500
    delay: 1
    finding-safe-location-delay: 1
    cooldown: 2
  level-4:
    world: "world"
    max-distance: 15000
    min-distance: 1500
    delay: 1
    finding-safe-location-delay: 1
    cooldown: 1
  level-5:
    world: "world"
    max-distance: 15000
    min-distance: 1500
    delay: 1
    finding-safe-location-delay: 1
    cooldown: 0
permissions:
  reload: randomtp.reload
  disable: randomtp.disable
  enable: randomtp.enable
  cooldown-1: randomtp.cooldown.1
  cooldown-2: randomtp.cooldown.2
  cooldown-3: randomtp.cooldown.3
  cooldown-4: randomtp.cooldown.4
  cooldown-5: randomtp.cooldown.5