name: SatisRandomTP
main: fr.flappy.randomtp.SatisRandomTP
version: '${project.version}'
author: Flappy
commands:
  randomteleport:
    description: Teleport to a random location.
    aliases: [rtp, randomtp, rdmtp]