name: SatisRandomTP
main: fr.flappy.randomtp.SatisRandomTP
version: 2.0-A1
author: Flappy
commands:
  randomteleport:
    description: Teleport to a random location.
    aliases: [rtp, randomtp, rdmtp]