name: SatisRandomTP
main: fr.flappy.randomtp.SatisRandomTP
version: 1.2-B2
author: Flappy
commands:
  randomteleport:
    description: Teleport to a random location.
    aliases: [rtp, randomtp, rdmtp]